### ISSUE TITLE
Firewall improvements

### ISSUE THREAD

**Issue by nko-sh** [NeoProtect/Roadmap#41]
Allow users to add:
- IPs (in CIDR format)
- ASNs

**Comment by koval01** [comment]
Neoprotect provides the ability to block IP addresses or whitelist them. But does not provide the ability to add to the CIDR blacklist

**Comment by koval01** [comment]
<img width="1186" alt="image (1)" src="https://user-images.githubusercontent.com/61350874/235624929-ab784dfd-3b41-4625-ac3d-c509c323795c.png">
<img width="1186" alt="image (2)" src="https://user-images.githubusercontent.com/61350874/235625337-352dc307-f8b0-4d04-b419-a1124f0b2a87.png">

I also think you should consider some specialized service for checking the IP type. Here I have attached two screenshots of the verification via ipinfo.io, my personal VPN server, and NordVPN's server. Both servers were classified as non-user. However, from both of these IPs, you can easily access the server where your AntiVPN is applied.

I understand that such IP type detection services cost money. But if it will be included in the company tariff, then I think it will become its strong advantage.

**Comment by nko-sh** [comment]
Thanks for your suggestions!
Using CIDR format for adding IPs is a very good idea which we will implement in the near future.
We'll also discuss the usage of other IP info services (like ipinfo.io) internally.

**Comment by ytendx** [comment]
Hey @koval01,
There currently is a check in progress which needs to be debugged still that will detect almost any and all vpn / proxy traffic due to ping calculations. (https://github.com/NeoProtect/Roadmap/issues/5) 
We could as well implement such thing into our proxy to determine if the player uses a vpn or not. (This would then be cached and used later on with a ttl)

Maybe we will implement this but we would need to discuss it internally.
